spring:
  application:
    name: eureka-server

server:
#  port: 3333
  port: 4444


eureka:
  instance:
    appname: eureka-server
#    hostname: eureka1
    hostname: eureka2
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
#    prefer-ip-address: true
  server:
    enable-self-preservation: false # 关闭保护机制
  client:
    register-with-eureka: true # 向注册中心注册服务
    fetch-registry: false # 检索服务
    service-url:
#      defaultZone: http://eureka1:4444/eureka/
      defaultZone: http://eureka1:3333/eureka/